-- Renovación de cuentas desde el catálogo web.
--
-- Hasta ahora un cliente solo podía renovar escribiéndole a un admin por WhatsApp.
-- Esta migración habilita la auto-renovación: el cliente se identifica por teléfono,
-- ve sus pantallas y su vencimiento, elige cuáles renovar y paga con los métodos que
-- ya existen. Una renovación NO asigna cuentas nuevas: extiende `clients.expires_at`
-- de las pantallas que el cliente ya tiene.
--
-- Diseño:
--   * orders.kind distingue 'purchase' (default, flujo actual) de 'renewal'. La leen
--     tanto el código JS (rutas de pago) como el trigger SQL de tickets manuales, para
--     decidir si entregar (fulfill_order) o extender (renew_order).
--   * renew_order extiende el vencimiento seteando expires_at EXPLÍCITO; el trigger
--     clients_set_expiry ya respeta un expires_at explícito (ver 20260617120000).
--   * La tabla renewals da idempotencia (no extender dos veces el mismo pago) e historial.
--   * lookup_renewable_accounts resuelve la identidad por teléfono normalizado (web y
--     wabot guardan E.164 '+58...'; normalizamos a dígitos por robustez).

-- 1. Tipo de orden -----------------------------------------------------------------
alter table orders add column if not exists kind text not null default 'purchase';

-- 2. Historial / idempotencia de renovaciones --------------------------------------
create table if not exists renewals (
	id             bigint generated by default as identity primary key,
	order_id       bigint not null references orders(id),
	client_id      bigint not null references clients(id),
	months         int    not null,
	old_expires_at timestamptz,
	new_expires_at timestamptz not null,
	created_at     timestamptz not null default now()
);

create index if not exists idx_renewals_order_id on renewals(order_id);
create index if not exists idx_renewals_client_id on renewals(client_id);

-- Solo el service-role (que bypassa RLS) escribe/lee renewals. Sin políticas =
-- anon/authenticated no acceden vía PostgREST.
alter table renewals enable row level security;
alter table renewals force row level security;

-- 3. Aplicar una renovación ya pagada ----------------------------------------------
-- Extiende expires_at de cada client referenciado en orders.items. Idempotente:
-- si ya hay renewals para la orden, devuelve lo aplicado sin volver a extender.
-- Política: si la pantalla sigue vigente, suma meses al vencimiento actual (no pierde
-- días pagos); si ya venció, cuenta desde hoy.
create or replace function renew_order(p_order_id bigint)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
	v_order      orders%rowtype;
	v_items      jsonb;
	v_item       jsonb;
	v_client_id  bigint;
	v_months     int;
	v_client     clients%rowtype;
	v_base       timestamptz;
	v_new        timestamptz;
	v_svc_name   text;
	v_result     jsonb := '[]'::jsonb;
begin
	select * into v_order from orders where id = p_order_id;
	if not found then
		raise exception 'ORDER_NOT_FOUND';
	end if;
	if v_order.status <> 'completed' then
		raise exception 'ORDER_NOT_COMPLETED';
	end if;
	if v_order.kind <> 'renewal' then
		raise exception 'ORDER_NOT_RENEWAL';
	end if;

	-- Idempotencia: ya aplicada → devolver el resumen existente.
	if exists (select 1 from renewals where order_id = p_order_id) then
		return coalesce((
			select jsonb_agg(jsonb_build_object(
				'service',    sv.comercial_name,
				'screen',     c.screen,
				'expires_at', r.new_expires_at
			) order by r.id)
			from renewals r
			join clients c on c.id = r.client_id
			left join services sv on sv.id = c.account_service
			where r.order_id = p_order_id
		), '[]'::jsonb);
	end if;

	v_items := coalesce(v_order.items::jsonb, '[]'::jsonb);

	for v_item in select * from jsonb_array_elements(v_items)
	loop
		v_client_id := (v_item->>'client_id')::bigint;
		v_months    := coalesce((v_item->>'months')::int, 1);
		if v_client_id is null then
			continue;
		end if;

		-- Bloquear la pantalla para evitar dobles extensiones concurrentes.
		select * into v_client from clients where id = v_client_id for update;
		if not found then
			continue;
		end if;

		v_base := greatest(now(), coalesce(v_client.expires_at, now()));
		v_new  := v_base + make_interval(months => v_months);

		-- expires_at explícito → clients_set_expiry NO lo recalcula.
		update clients set expires_at = v_new, paid = true where id = v_client_id;

		insert into renewals (order_id, client_id, months, old_expires_at, new_expires_at)
		values (p_order_id, v_client_id, v_months, v_client.expires_at, v_new);

		select comercial_name into v_svc_name from services where id = v_client.account_service;

		v_result := v_result || jsonb_build_object(
			'service',    v_svc_name,
			'screen',     v_client.screen,
			'expires_at', v_new
		);
	end loop;

	return v_result;
end;
$$;

grant execute on function renew_order(bigint) to service_role;

-- 4. Buscar las pantallas renovables de un teléfono --------------------------------
-- Identidad por teléfono (único dato presente en TODOS los clients: web y wabot).
-- Normaliza a dígitos y matchea por los últimos 10 (núcleo nacional) para tolerar
-- diferencias de código de país / prefijo. Devuelve SOLO campos no sensibles
-- (nunca mail/password). Excluye clientes de reseller (los maneja su reseller).
create or replace function lookup_renewable_accounts(p_phone text)
returns table (
	client_id    bigint,
	service_id   int,
	service      text,
	screen       int,
	expires_at   timestamptz,
	screen_price numeric
)
language sql
stable
security definer
set search_path = public
as $$
	with norm as (
		select right(regexp_replace(coalesce(p_phone, ''), '\D', '', 'g'), 10) as digits
	)
	select
		c.id                                   as client_id,
		c.account_service                      as service_id,
		sv.comercial_name                      as service,
		c.screen                               as screen,
		c.expires_at                           as expires_at,
		coalesce(sv.screen_price, c.amount, 0) as screen_price
	from clients c
	join services sv on sv.id = c.account_service
	cross join norm
	where length(norm.digits) >= 7
		and right(regexp_replace(coalesce(c.phone, ''), '\D', '', 'g'), 10) = norm.digits
		and coalesce(c.is_reseller_customer, false) = false
	order by c.expires_at asc nulls last;
$$;

grant execute on function lookup_renewable_accounts(text) to service_role;

-- 5. Recrear el trigger de tickets manuales para bifurcar compra vs renovación ------
-- Idéntico a 20260616203320, salvo que en 'approved' decide entre entregar (compra)
-- o extender (renovación) según orders.kind.
create or replace function on_web_ticket_resolved()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare
	v_kind text;
begin
	if NEW.source <> 'web' or NEW.type <> 'payment' then
		return NEW;
	end if;
	if NEW.status is not distinct from OLD.status then
		return NEW;
	end if;
	if NEW.order_id is null then
		return NEW;
	end if;

	if NEW.status = 'approved' then
		update orders set status = 'completed'
		where id = NEW.order_id and status <> 'completed';

		select kind into v_kind from orders where id = NEW.order_id;

		begin
			if v_kind = 'renewal' then
				perform renew_order(NEW.order_id);
			else
				perform fulfill_order(NEW.order_id);
			end if;
		exception when others then
			raise warning 'post-approval (% ) failed for order %: %', v_kind, NEW.order_id, sqlerrm;
		end;
	elsif NEW.status = 'rejected' then
		update orders set status = 'failed'
		where id = NEW.order_id and status not in ('completed', 'failed');
	end if;

	return NEW;
end;
$$;

drop trigger if exists trg_web_ticket_resolved on tickets;
create trigger trg_web_ticket_resolved
	after update on tickets
	for each row
	execute function on_web_ticket_resolved();
